local grass_dirt = alien_biomes.list_tiles(alien_biomes.require_tag(alien_biomes.all_tiles(), {"grass", "dirt"}))
local grass = alien_biomes.list_tiles(alien_biomes.require_tag(alien_biomes.all_tiles(), {"grass"}))

local trees = {
  -- wetland
  {
    name = "tree-wetland-a",
    model = "oaktapus",
    locale = "lemon",
    noise = "trees-1",
    temperature_low = 0.65,
    temperature_high = 1,
    aux_low = 0,
    aux_high = 0.2,
    water_band = 4,
    density = 4,
    colors = {
      {r = 241, g = 238, b = 14},
      {r = 245, g = 165, b = 11},
      {r = 105, g = 184, b = 40}
    },
    tags = {"green", "yellow"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-e",
    model = "04",
    locale = "evergreen",
    noise = "trees-5",
    temperature_low = 0.35,
    temperature_high = 0.9,
    aux_low = 0.4,
    aux_high = 0.8,
    water_band = 4,
    density = 4,
    colors = {
      {r = 218, g = 187, b = 44},
      {r = 79, g = 119, b = 21},
      {r = 105, g = 184, b = 40},
    },
    tags = {"green"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-g",
    model = "05",
    locale = "arsenic",
    noise = "trees-7",
    temperature_low = 0.4,
    temperature_high = 0.65,
    aux_low = 0.0,
    aux_high = 0.2,
    water_band = 4,
    density = 4,
    colors = {
      {r = 245, g = 165, b = 11},
      {r = 241, g = 238, b = 14},
      {r = 142, g = 99, b = 23},
    },
    tags = {"yellow"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-i",
    model = "mangrove",
    locale = "bile",
    noise = "trees-9",
    temperature_low = 0.35,
    temperature_high = 0.4,
    aux_low = 0.0,
    aux_high = 0.2,
    water_band = 4,
    density = 4,
    colors = {
      {r = 150, g = 134, b = 46},
      {r = 70, g = 76, b = 23},
      {r = 94, g = 125, b = 20},
      {r = 109, g = 122, b = 56},
      {r = 105, g = 164, b = 40},
      {r = 79, g = 119, b = 21},
    },
    tags = {"green"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-m",
    model = "07",
    locale = "jade",
    noise = "trees-4",
    temperature_low = 0.0,
    temperature_high = 0.25,
    aux_low = 0.0,
    aux_high = 0.2,
    water_band = 4,
    density = 4,
    colors = {
      {r = 36, g = 225, b = 157},
      {r = 176, g = 220, b = 155},
      {r = 105, g = 184, b = 40},
    },
    tags = {"green"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-n",
    model = "mangrove",
    locale = "cyanide",
    noise = "trees-5",
    temperature_low = 0.0,
    temperature_high = 0.1,
    aux_low = 0.2,
    aux_high = 0.6,
    water_band = 4,
    density = 4,
    colors = {
      {r = 65, g = 123, b = 122},
      {r = 43, g = 122, b = 89},
      {r = 75, g = 110, b = 123},
      {r = 17, g = 62, b = 5},
      {r = 103, g = 149, b = 156},
    },
    tags = {"green"},
    tile_restriction = grass,
  },
  {
    name = "tree-wetland-o",
    model = "01",
    locale = "tickling",
    noise = "trees-6",
    temperature_low = 0.0,
    temperature_high = 0.1,
    aux_low = 0.6,
    aux_high = 1,
    water_band = 4,
    density = 4,
    colors = {
      {r = 17, g = 62, b = 5},
      {r = 69, g = 73, b = 9},
      {r = 105, g = 184, b = 40},
    },
    tags = {"green"},
    tile_restriction = grass,
  },

  -- Grassland
  {
    name = "tree-grassland-a",
    model = "ash",
    locale = "olive",
    noise = "trees-7",
    temperature_low = 0.6,
    temperature_high = 1,
    aux_low = 0,
    aux_high = 0.15,
    water_band = 3,
    density = 3,
    colors = {
      {r = 165, g = 184, b = 40},
      {r = 79, g = 119, b = 21},
      {r = 69, g = 73, b = 9},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-grassland-f",
    model = "ash",
    locale = "sunleaf",
    noise = "trees-3",
    temperature_low = 0.6,
    temperature_high = 0.85,
    aux_low = 0.15,
    aux_high = 0.35,
    water_band = 3,
    density = 3,
    colors = {
      {r = 218, g = 187, b = 44},
      {r = 245, g = 165, b = 11},
      {r = 142, g = 99, b = 23},
    },
    tags = {"yellow"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-grassland-g",
    model = "ash",
    locale = "springleaf",
    noise = "trees-4",
    temperature_low = 0.4,
    temperature_high = 0.75,
    aux_low = 0.35,
    aux_high = 0.55,
    water_band = 3,
    density = 3,
    colors = {
      {r = 69, g = 73, b = 9},
      {r = 165, g = 184, b = 40},
      {r = 79, g = 119, b = 21},
      {r = 210, g = 185, b = 48},
      {r = 218, g = 187, b = 44},
    },
    tags = {"green", "yellow"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-grassland-h",
    model = "05",
    locale = "broadleaf",
    noise = "trees-5",
    temperature_low = 0.1,
    temperature_high = 0.75,
    aux_low = 0.55,
    aux_high = 0.65,
    water_band = 3,
    density = 3,
    colors = {
      {r = 79, g = 119, b = 21},
      {r = 165, g = 184, b = 40},
      {r = 69, g = 73, b = 9},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-grassland-j",
    model = "08",
    locale = "starleaf",
    noise = "trees-8",
    temperature_low = 0.4,
    temperature_high = 0.6,
    aux_low = 0,
    aux_high = 0.3,
    water_band = 3,
    density = 3,
    colors = {
      {r = 218, g = 187, b = 44},
      {r = 79, g = 119, b = 21},
      {r = 105, g = 184, b = 40},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-grassland-k",
    model = "02",
    locale = "emerald",
    noise = "trees-9",
    temperature_low = 0.1,
    temperature_high = 0.4,
    aux_low = 0,
    aux_high = 0.3,
    water_band = 3,
    density = 3,
    colors = {
      {r = 76, g = 61, b = 16},
      {r = 69, g = 137, b = 69},
      {r = 152, g = 119, b = 33},
      {r = 109, g = 132, b = 43},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },


  -- dryland
  {
    name = "tree-dryland-b",
    model = "04",
    locale = "succulent",
    noise = "trees-8",
    temperature_low = 0.85,
    temperature_high = 1,
    aux_low = 0.4,
    aux_high = 0.7,
    water_band = 2,
    density = 1,
    colors = {
      {r = 17, g = 62, b = 5},
      {r = 142, g = 99, b = 23},
      {r = 79, g = 119, b = 21},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-dryland-e",
    model = "oaktapus",
    locale = "mint",
    noise = "trees-2",
    temperature_low = 0.45,
    temperature_high = 0.85,
    aux_low = 0,
    aux_high = 0.2,
    water_band = 2,
    density = 1,
    colors = {
      {r = 105, g = 184, b = 40},
      {r = 176, g = 220, b = 165},
      {r = 142, g = 99, b = 23},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-dryland-f",
    model = "08",
    locale = "spinleaf",
    noise = "trees-3",
    temperature_low = 0.7,
    temperature_high = 0.85,
    aux_low = 0.2,
    aux_high = 0.7,
    water_band = 2,
    density = 1,
    colors = {
      {r = 245, g = 165, b = 11},
      {r = 241, g = 238, b = 14},
      {r = 142, g = 99, b = 23},
    },
    tags = {"green", "yellow"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-dryland-g",
    model = "oaktapus",
    locale = "mottled",
    noise = "trees-4",
    temperature_low = 0.45,
    temperature_high = 0.7,
    aux_low = 0.2,
    aux_high = 0.5,
    water_band = 2,
    density = 1,
    colors = {
      {r = 174, g = 156, b = 56},
      {r = 163, g = 88, b = 33},
      {r = 152, g = 99, b = 23},
      {r = 79, g = 119, b = 21},
    },
    tags = {"green", "yellow"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-dryland-j",
    model = "01",
    locale = "fluffy",
    noise = "trees-7",
    temperature_low = 0.0,
    temperature_high = 0.45,
    aux_low = 0.0,
    aux_high = 0.15,
    water_band = 2,
    density = 1,
    colors = {
      {r = 176, g = 220, b = 165},
      {r = 105, g = 184, b = 40},
      {r = 75, g = 92, b = 123},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },
  {
    name = "tree-dryland-k",
    model = "greypine",
    locale = "mothwing",
    noise = "trees-8",
    temperature_low = 0.15,
    temperature_high = 0.45,
    aux_low = 0.15,
    aux_high = 0.45,
    water_band = 2,
    density = 1,
    colors = {
      {r = 17, g = 62, b = 5},
      {r = 79, g = 119, b = 21},
      {r = 75, g = 92, b = 123},
    },
    tags = {"green"},
    tile_restriction = grass_dirt,
  },

  -- desert
  {
    name = "tree-desert-a",
    model = "08",
    locale = "cactuar",
    noise = "trees-4",
    temperature_low = 0.75,
    temperature_high = 1,
    aux_low = 0.0,
    aux_high = 0.15,
    water_band = 1,
    density = 1,
    colors = {
      {r = 142, g = 99, b = 23},
      {r = 241, g = 238, b = 14},
      {r = 69, g = 73, b = 9},
    },
    tags = {"green"}
  },
  {
    name = "tree-desert-d",
    model = "pear",
    locale = "dragonfly",
    noise = "trees-7",
    temperature_low = 0.75,
    temperature_high = 1,
    aux_low = 0.7,
    aux_high = 0.9,
    water_band = 1,
    density = 1,
    colors = {
      {r = 79, g = 119, b = 21},
      {r = 176, g = 220, b = 165},
      {r = 76, g = 61, b = 16},
    },
    tags = {"green"}
  },
  {
    name = "tree-desert-e",
    model = "08",
    locale = "deeproot",
    noise = "trees-8",
    temperature_low = 0.75,
    temperature_high = 1,
    aux_low = 0.9,
    aux_high = 1,
    water_band = 1,
    density = 1,
    colors = {
      {r = 167, g = 198, b = 86},
      {r = 176, g = 220, b = 165},
      {r = 79, g = 119, b = 21},
    },
    tags = {"green"}
  },
  {
    name = "tree-desert-f",
    model = "pear",
    locale = "sporepuff",
    noise = "trees-9",
    temperature_low = 0.5,
    temperature_high = 0.8,
    aux_low = 0.15,
    aux_high = 0.45,
    water_band = 1,
    density = 1,
    colors = {
      {r = 150, g = 150, b = 20},
      {r = 69, g = 73, b = 9},
      {r = 79, g = 119, b = 21},
    },
    tags = {"yellow"}
  },
  {
    name = "tree-desert-g",
    model = "06",
    locale = "hangman",
    noise = "trees-1",
    temperature_low = 0.45,
    temperature_high = 0.75,
    aux_low = 0.0,
    aux_high = 0.15,
    water_band = 1,
    density = 1,
    colors = {
      {r = 184, g = 31, b = 31},
      {r = 55, g = 22, b = 74},
      {r = 245, g = 165, b = 11},
    },
    tags = {"green"}
  },
  -- frozen
  {
    name = "tree-snow-a",
    model = "conifer-01",
    locale = "iceblade",
    noise = "trees-1",
    stump = "tree-02-stump",
    temperature_low = -0.15,
    temperature_high = 0,
    aux_low = 0,
    aux_high = 1,
    density = 2,
    colors = {
      {r = 255, g = 255, b = 255},
      {r = 167, g = 198, b = 220},
      {r = 32, g = 76, b = 42},
      {r = 17, g = 62, b = 5},
    },
    tags = {"green"},
    tile_restriction = alien_biomes.list_tiles(alien_biomes.exclude_tags(alien_biomes.all_tiles(), {"ice", "volcanic", "sand"}))
  },

  -- palm
  {
    name = "tree-palm-a",
    model = "palm",
    locale = "paradise",
    noise = "trees-3",
    stump = "tree-02-stump",
    elevation_low = 0,
    elevation_high = 2,
    temperature_high = 1,
    temperature_low = 0.25,
    temperature_high = 1,
    water_low = 0.4,
    water_high = 1,
    aux_low = 0,
    aux_high = 0.5,
    density = 1,
    colors = {
      {r = 85, g = 114, b = 47},
      {r = 100, g = 127, b = 52},
      {r = 63, g = 118, b = 10},
      {r = 101, g = 106, b = 23}
    },
    tags = {"green"},
    tile_restriction = alien_biomes.list_tiles(alien_biomes.require_tag(alien_biomes.all_tiles(), {"sand"}))
  },
}
return trees
